/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AiPlannerRouteImport } from './routes/ai-planner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as CancelIdRouteImport } from './routes/cancel.$id'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AiPlannerProcessingRouteImport } from './routes/ai-planner.processing'
import { Route as AiPlannerPreferencesRouteImport } from './routes/ai-planner.preferences'
import { Route as AiPlannerItineraryRouteImport } from './routes/ai-planner.itinerary'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerRoute = AiPlannerRouteImport.update({
  id: '/ai-planner',
  path: '/ai-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const CancelIdRoute = CancelIdRouteImport.update({
  id: '/cancel/$id',
  path: '/cancel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AiPlannerProcessingRoute = AiPlannerProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AiPlannerRoute,
} as any)
const AiPlannerPreferencesRoute = AiPlannerPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AiPlannerRoute,
} as any)
const AiPlannerItineraryRoute = AiPlannerItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => AiPlannerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/contact'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/notifications'
    | '/packages'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/trips/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/contact'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/notifications'
    | '/packages'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/trips/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/contact'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/notifications'
    | '/packages'
    | '/profile'
    | '/search'
    | '/sitemap.xml'
    | '/wishlist'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/trips/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiPlannerRoute: typeof AiPlannerRouteWithChildren
  BlogsRoute: typeof BlogsRouteWithChildren
  BookingRoute: typeof BookingRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  NotificationsRoute: typeof NotificationsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
  CancelIdRoute: typeof CancelIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  TripsIdRoute: typeof TripsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner': {
      id: '/ai-planner'
      path: '/ai-planner'
      fullPath: '/ai-planner'
      preLoaderRoute: typeof AiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/cancel/$id': {
      id: '/cancel/$id'
      path: '/cancel/$id'
      fullPath: '/cancel/$id'
      preLoaderRoute: typeof CancelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/ai-planner/processing': {
      id: '/ai-planner/processing'
      path: '/processing'
      fullPath: '/ai-planner/processing'
      preLoaderRoute: typeof AiPlannerProcessingRouteImport
      parentRoute: typeof AiPlannerRoute
    }
    '/ai-planner/preferences': {
      id: '/ai-planner/preferences'
      path: '/preferences'
      fullPath: '/ai-planner/preferences'
      preLoaderRoute: typeof AiPlannerPreferencesRouteImport
      parentRoute: typeof AiPlannerRoute
    }
    '/ai-planner/itinerary': {
      id: '/ai-planner/itinerary'
      path: '/itinerary'
      fullPath: '/ai-planner/itinerary'
      preLoaderRoute: typeof AiPlannerItineraryRouteImport
      parentRoute: typeof AiPlannerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiPlannerRouteChildren {
  AiPlannerItineraryRoute: typeof AiPlannerItineraryRoute
  AiPlannerPreferencesRoute: typeof AiPlannerPreferencesRoute
  AiPlannerProcessingRoute: typeof AiPlannerProcessingRoute
}

const AiPlannerRouteChildren: AiPlannerRouteChildren = {
  AiPlannerItineraryRoute: AiPlannerItineraryRoute,
  AiPlannerPreferencesRoute: AiPlannerPreferencesRoute,
  AiPlannerProcessingRoute: AiPlannerProcessingRoute,
}

const AiPlannerRouteWithChildren = AiPlannerRoute._addFileChildren(
  AiPlannerRouteChildren,
)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiPlannerRoute: AiPlannerRouteWithChildren,
  BlogsRoute: BlogsRouteWithChildren,
  BookingRoute: BookingRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  NotificationsRoute: NotificationsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
  CancelIdRoute: CancelIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  TripsIdRoute: TripsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
