/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TemplesRouteImport } from './routes/temples'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentPortalRouteImport } from './routes/student-portal'
import { Route as StatesRouteImport } from './routes/states'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PilgrimageRouteImport } from './routes/pilgrimage'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as FoodRouteImport } from './routes/food'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectivityRouteImport } from './routes/connectivity'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AiPlannerRouteImport } from './routes/ai-planner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as TemplesSlugRouteImport } from './routes/temples.$slug'
import { Route as StudentsSlugRouteImport } from './routes/students.$slug'
import { Route as StatesSlugRouteImport } from './routes/states.$slug'
import { Route as SportsSlugRouteImport } from './routes/sports.$slug'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as HeritageSlugRouteImport } from './routes/heritage.$slug'
import { Route as GovernmentSlugRouteImport } from './routes/government.$slug'
import { Route as FoodSlugRouteImport } from './routes/food.$slug'
import { Route as FestivalsSlugRouteImport } from './routes/festivals.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as CancelIdRouteImport } from './routes/cancel.$id'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AiPlannerProcessingRouteImport } from './routes/ai-planner.processing'
import { Route as AiPlannerPreferencesRouteImport } from './routes/ai-planner.preferences'
import { Route as AiPlannerItineraryRouteImport } from './routes/ai-planner.itinerary'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainingRouteImport } from './routes/admin.training'
import { Route as AdminTemplesRouteImport } from './routes/admin.temples'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSportsRouteImport } from './routes/admin.sports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchemesRouteImport } from './routes/admin.schemes'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHeritageRouteImport } from './routes/admin.heritage'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFoodRouteImport } from './routes/admin.food'
import { Route as AdminDestinationsRouteImport } from './routes/admin.destinations'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminBankingRouteImport } from './routes/admin.banking'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesRoute = TemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PilgrimageRoute = PilgrimageRouteImport.update({
  id: '/pilgrimage',
  path: '/pilgrimage',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectivityRoute = ConnectivityRouteImport.update({
  id: '/connectivity',
  path: '/connectivity',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerRoute = AiPlannerRouteImport.update({
  id: '/ai-planner',
  path: '/ai-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesSlugRoute = TemplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TemplesRoute,
} as any)
const StudentsSlugRoute = StudentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudentsRoute,
} as any)
const StatesSlugRoute = StatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StatesRoute,
} as any)
const SportsSlugRoute = SportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SportsRoute,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const HeritageSlugRoute = HeritageSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HeritageRoute,
} as any)
const GovernmentSlugRoute = GovernmentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GovernmentRoute,
} as any)
const FoodSlugRoute = FoodSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FoodRoute,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FestivalsRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const CancelIdRoute = CancelIdRouteImport.update({
  id: '/cancel/$id',
  path: '/cancel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlannerProcessingRoute = AiPlannerProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AiPlannerRoute,
} as any)
const AiPlannerPreferencesRoute = AiPlannerPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AiPlannerRoute,
} as any)
const AiPlannerItineraryRoute = AiPlannerItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => AiPlannerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplesRoute = AdminTemplesRouteImport.update({
  id: '/temples',
  path: '/temples',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSportsRoute = AdminSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchemesRoute = AdminSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeritageRoute = AdminHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodRoute = AdminFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBankingRoute = AdminBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/connectivity': typeof ConnectivityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/festivals': typeof FestivalsRouteWithChildren
  '/food': typeof FoodRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/pilgrimage': typeof PilgrimageRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRouteWithChildren
  '/states': typeof StatesRouteWithChildren
  '/student-portal': typeof StudentPortalRoute
  '/students': typeof StudentsRouteWithChildren
  '/temples': typeof TemplesRouteWithChildren
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/food': typeof AdminFoodRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/heritage': typeof AdminHeritageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/food/$slug': typeof FoodSlugRoute
  '/government/$slug': typeof GovernmentSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/students/$slug': typeof StudentsSlugRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/connectivity': typeof ConnectivityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/festivals': typeof FestivalsRouteWithChildren
  '/food': typeof FoodRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/pilgrimage': typeof PilgrimageRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRouteWithChildren
  '/states': typeof StatesRouteWithChildren
  '/student-portal': typeof StudentPortalRoute
  '/students': typeof StudentsRouteWithChildren
  '/temples': typeof TemplesRouteWithChildren
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/food': typeof AdminFoodRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/heritage': typeof AdminHeritageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/food/$slug': typeof FoodSlugRoute
  '/government/$slug': typeof GovernmentSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/students/$slug': typeof StudentsSlugRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-planner': typeof AiPlannerRouteWithChildren
  '/blogs': typeof BlogsRouteWithChildren
  '/booking': typeof BookingRoute
  '/bookings': typeof BookingsRoute
  '/certificates': typeof CertificatesRoute
  '/connectivity': typeof ConnectivityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/festivals': typeof FestivalsRouteWithChildren
  '/food': typeof FoodRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/heritage': typeof HeritageRouteWithChildren
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/packages': typeof PackagesRouteWithChildren
  '/pilgrimage': typeof PilgrimageRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRouteWithChildren
  '/states': typeof StatesRouteWithChildren
  '/student-portal': typeof StudentPortalRoute
  '/students': typeof StudentsRouteWithChildren
  '/temples': typeof TemplesRouteWithChildren
  '/training': typeof TrainingRoute
  '/welcome': typeof WelcomeRoute
  '/wishlist': typeof WishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/food': typeof AdminFoodRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/heritage': typeof AdminHeritageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sports': typeof AdminSportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/temples': typeof AdminTemplesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-planner/itinerary': typeof AiPlannerItineraryRoute
  '/ai-planner/preferences': typeof AiPlannerPreferencesRoute
  '/ai-planner/processing': typeof AiPlannerProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/cancel/$id': typeof CancelIdRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/food/$slug': typeof FoodSlugRoute
  '/government/$slug': typeof GovernmentSlugRoute
  '/heritage/$slug': typeof HeritageSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/sports/$slug': typeof SportsSlugRoute
  '/states/$slug': typeof StatesSlugRoute
  '/students/$slug': typeof StudentsSlugRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/certificates'
    | '/connectivity'
    | '/contact'
    | '/dashboard'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/festivals'
    | '/food'
    | '/government'
    | '/heritage'
    | '/map'
    | '/notifications'
    | '/packages'
    | '/pilgrimage'
    | '/profile'
    | '/restaurants'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/sports'
    | '/states'
    | '/student-portal'
    | '/students'
    | '/temples'
    | '/training'
    | '/welcome'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banking'
    | '/admin/blogs'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/food'
    | '/admin/gallery'
    | '/admin/heritage'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/students'
    | '/admin/temples'
    | '/admin/training'
    | '/admin/users'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/festivals/$slug'
    | '/food/$slug'
    | '/government/$slug'
    | '/heritage/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/sports/$slug'
    | '/states/$slug'
    | '/students/$slug'
    | '/temples/$slug'
    | '/trips/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/certificates'
    | '/connectivity'
    | '/contact'
    | '/dashboard'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/festivals'
    | '/food'
    | '/government'
    | '/heritage'
    | '/map'
    | '/notifications'
    | '/packages'
    | '/pilgrimage'
    | '/profile'
    | '/restaurants'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/sports'
    | '/states'
    | '/student-portal'
    | '/students'
    | '/temples'
    | '/training'
    | '/welcome'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banking'
    | '/admin/blogs'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/food'
    | '/admin/gallery'
    | '/admin/heritage'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/students'
    | '/admin/temples'
    | '/admin/training'
    | '/admin/users'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/festivals/$slug'
    | '/food/$slug'
    | '/government/$slug'
    | '/heritage/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/sports/$slug'
    | '/states/$slug'
    | '/students/$slug'
    | '/temples/$slug'
    | '/trips/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-planner'
    | '/blogs'
    | '/booking'
    | '/bookings'
    | '/certificates'
    | '/connectivity'
    | '/contact'
    | '/dashboard'
    | '/design-system'
    | '/destinations'
    | '/faq'
    | '/festivals'
    | '/food'
    | '/government'
    | '/heritage'
    | '/map'
    | '/notifications'
    | '/packages'
    | '/pilgrimage'
    | '/profile'
    | '/restaurants'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/sports'
    | '/states'
    | '/student-portal'
    | '/students'
    | '/temples'
    | '/training'
    | '/welcome'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banking'
    | '/admin/blogs'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/food'
    | '/admin/gallery'
    | '/admin/heritage'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/sports'
    | '/admin/students'
    | '/admin/temples'
    | '/admin/training'
    | '/admin/users'
    | '/ai-planner/itinerary'
    | '/ai-planner/preferences'
    | '/ai-planner/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset'
    | '/auth/signup'
    | '/blogs/$slug'
    | '/cancel/$id'
    | '/destinations/$slug'
    | '/festivals/$slug'
    | '/food/$slug'
    | '/government/$slug'
    | '/heritage/$slug'
    | '/packages/$slug'
    | '/reviews/new'
    | '/sports/$slug'
    | '/states/$slug'
    | '/students/$slug'
    | '/temples/$slug'
    | '/trips/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiPlannerRoute: typeof AiPlannerRouteWithChildren
  BlogsRoute: typeof BlogsRouteWithChildren
  BookingRoute: typeof BookingRoute
  BookingsRoute: typeof BookingsRoute
  CertificatesRoute: typeof CertificatesRoute
  ConnectivityRoute: typeof ConnectivityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  FestivalsRoute: typeof FestivalsRouteWithChildren
  FoodRoute: typeof FoodRouteWithChildren
  GovernmentRoute: typeof GovernmentRouteWithChildren
  HeritageRoute: typeof HeritageRouteWithChildren
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PilgrimageRoute: typeof PilgrimageRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantsRoute: typeof RestaurantsRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRouteWithChildren
  StatesRoute: typeof StatesRouteWithChildren
  StudentPortalRoute: typeof StudentPortalRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TemplesRoute: typeof TemplesRouteWithChildren
  TrainingRoute: typeof TrainingRoute
  WelcomeRoute: typeof WelcomeRoute
  WishlistRoute: typeof WishlistRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CancelIdRoute: typeof CancelIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  TripsIdRoute: typeof TripsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples': {
      id: '/temples'
      path: '/temples'
      fullPath: '/temples'
      preLoaderRoute: typeof TemplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilgrimage': {
      id: '/pilgrimage'
      path: '/pilgrimage'
      fullPath: '/pilgrimage'
      preLoaderRoute: typeof PilgrimageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectivity': {
      id: '/connectivity'
      path: '/connectivity'
      fullPath: '/connectivity'
      preLoaderRoute: typeof ConnectivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner': {
      id: '/ai-planner'
      path: '/ai-planner'
      fullPath: '/ai-planner'
      preLoaderRoute: typeof AiPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/$slug': {
      id: '/temples/$slug'
      path: '/$slug'
      fullPath: '/temples/$slug'
      preLoaderRoute: typeof TemplesSlugRouteImport
      parentRoute: typeof TemplesRoute
    }
    '/students/$slug': {
      id: '/students/$slug'
      path: '/$slug'
      fullPath: '/students/$slug'
      preLoaderRoute: typeof StudentsSlugRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/states/$slug': {
      id: '/states/$slug'
      path: '/$slug'
      fullPath: '/states/$slug'
      preLoaderRoute: typeof StatesSlugRouteImport
      parentRoute: typeof StatesRoute
    }
    '/sports/$slug': {
      id: '/sports/$slug'
      path: '/$slug'
      fullPath: '/sports/$slug'
      preLoaderRoute: typeof SportsSlugRouteImport
      parentRoute: typeof SportsRoute
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/heritage/$slug': {
      id: '/heritage/$slug'
      path: '/$slug'
      fullPath: '/heritage/$slug'
      preLoaderRoute: typeof HeritageSlugRouteImport
      parentRoute: typeof HeritageRoute
    }
    '/government/$slug': {
      id: '/government/$slug'
      path: '/$slug'
      fullPath: '/government/$slug'
      preLoaderRoute: typeof GovernmentSlugRouteImport
      parentRoute: typeof GovernmentRoute
    }
    '/food/$slug': {
      id: '/food/$slug'
      path: '/$slug'
      fullPath: '/food/$slug'
      preLoaderRoute: typeof FoodSlugRouteImport
      parentRoute: typeof FoodRoute
    }
    '/festivals/$slug': {
      id: '/festivals/$slug'
      path: '/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof FestivalsRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/cancel/$id': {
      id: '/cancel/$id'
      path: '/cancel/$id'
      fullPath: '/cancel/$id'
      preLoaderRoute: typeof CancelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-planner/processing': {
      id: '/ai-planner/processing'
      path: '/processing'
      fullPath: '/ai-planner/processing'
      preLoaderRoute: typeof AiPlannerProcessingRouteImport
      parentRoute: typeof AiPlannerRoute
    }
    '/ai-planner/preferences': {
      id: '/ai-planner/preferences'
      path: '/preferences'
      fullPath: '/ai-planner/preferences'
      preLoaderRoute: typeof AiPlannerPreferencesRouteImport
      parentRoute: typeof AiPlannerRoute
    }
    '/ai-planner/itinerary': {
      id: '/ai-planner/itinerary'
      path: '/itinerary'
      fullPath: '/ai-planner/itinerary'
      preLoaderRoute: typeof AiPlannerItineraryRouteImport
      parentRoute: typeof AiPlannerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temples': {
      id: '/admin/temples'
      path: '/temples'
      fullPath: '/admin/temples'
      preLoaderRoute: typeof AdminTemplesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sports': {
      id: '/admin/sports'
      path: '/sports'
      fullPath: '/admin/sports'
      preLoaderRoute: typeof AdminSportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schemes': {
      id: '/admin/schemes'
      path: '/schemes'
      fullPath: '/admin/schemes'
      preLoaderRoute: typeof AdminSchemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/heritage': {
      id: '/admin/heritage'
      path: '/heritage'
      fullPath: '/admin/heritage'
      preLoaderRoute: typeof AdminHeritageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/food': {
      id: '/admin/food'
      path: '/food'
      fullPath: '/admin/food'
      preLoaderRoute: typeof AdminFoodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banking': {
      id: '/admin/banking'
      path: '/banking'
      fullPath: '/admin/banking'
      preLoaderRoute: typeof AdminBankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBankingRoute: typeof AdminBankingRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminFoodRoute: typeof AdminFoodRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHeritageRoute: typeof AdminHeritageRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSchemesRoute: typeof AdminSchemesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSportsRoute: typeof AdminSportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTemplesRoute: typeof AdminTemplesRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBankingRoute: AdminBankingRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminFoodRoute: AdminFoodRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHeritageRoute: AdminHeritageRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSchemesRoute: AdminSchemesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSportsRoute: AdminSportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTemplesRoute: AdminTemplesRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiPlannerRouteChildren {
  AiPlannerItineraryRoute: typeof AiPlannerItineraryRoute
  AiPlannerPreferencesRoute: typeof AiPlannerPreferencesRoute
  AiPlannerProcessingRoute: typeof AiPlannerProcessingRoute
}

const AiPlannerRouteChildren: AiPlannerRouteChildren = {
  AiPlannerItineraryRoute: AiPlannerItineraryRoute,
  AiPlannerPreferencesRoute: AiPlannerPreferencesRoute,
  AiPlannerProcessingRoute: AiPlannerProcessingRoute,
}

const AiPlannerRouteWithChildren = AiPlannerRoute._addFileChildren(
  AiPlannerRouteChildren,
)

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface FestivalsRouteChildren {
  FestivalsSlugRoute: typeof FestivalsSlugRoute
}

const FestivalsRouteChildren: FestivalsRouteChildren = {
  FestivalsSlugRoute: FestivalsSlugRoute,
}

const FestivalsRouteWithChildren = FestivalsRoute._addFileChildren(
  FestivalsRouteChildren,
)

interface FoodRouteChildren {
  FoodSlugRoute: typeof FoodSlugRoute
}

const FoodRouteChildren: FoodRouteChildren = {
  FoodSlugRoute: FoodSlugRoute,
}

const FoodRouteWithChildren = FoodRoute._addFileChildren(FoodRouteChildren)

interface GovernmentRouteChildren {
  GovernmentSlugRoute: typeof GovernmentSlugRoute
}

const GovernmentRouteChildren: GovernmentRouteChildren = {
  GovernmentSlugRoute: GovernmentSlugRoute,
}

const GovernmentRouteWithChildren = GovernmentRoute._addFileChildren(
  GovernmentRouteChildren,
)

interface HeritageRouteChildren {
  HeritageSlugRoute: typeof HeritageSlugRoute
}

const HeritageRouteChildren: HeritageRouteChildren = {
  HeritageSlugRoute: HeritageSlugRoute,
}

const HeritageRouteWithChildren = HeritageRoute._addFileChildren(
  HeritageRouteChildren,
)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

interface SportsRouteChildren {
  SportsSlugRoute: typeof SportsSlugRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSlugRoute: SportsSlugRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface StatesRouteChildren {
  StatesSlugRoute: typeof StatesSlugRoute
}

const StatesRouteChildren: StatesRouteChildren = {
  StatesSlugRoute: StatesSlugRoute,
}

const StatesRouteWithChildren =
  StatesRoute._addFileChildren(StatesRouteChildren)

interface StudentsRouteChildren {
  StudentsSlugRoute: typeof StudentsSlugRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsSlugRoute: StudentsSlugRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface TemplesRouteChildren {
  TemplesSlugRoute: typeof TemplesSlugRoute
}

const TemplesRouteChildren: TemplesRouteChildren = {
  TemplesSlugRoute: TemplesSlugRoute,
}

const TemplesRouteWithChildren =
  TemplesRoute._addFileChildren(TemplesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiPlannerRoute: AiPlannerRouteWithChildren,
  BlogsRoute: BlogsRouteWithChildren,
  BookingRoute: BookingRoute,
  BookingsRoute: BookingsRoute,
  CertificatesRoute: CertificatesRoute,
  ConnectivityRoute: ConnectivityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  FestivalsRoute: FestivalsRouteWithChildren,
  FoodRoute: FoodRouteWithChildren,
  GovernmentRoute: GovernmentRouteWithChildren,
  HeritageRoute: HeritageRouteWithChildren,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PilgrimageRoute: PilgrimageRoute,
  ProfileRoute: ProfileRoute,
  RestaurantsRoute: RestaurantsRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRouteWithChildren,
  StatesRoute: StatesRouteWithChildren,
  StudentPortalRoute: StudentPortalRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TemplesRoute: TemplesRouteWithChildren,
  TrainingRoute: TrainingRoute,
  WelcomeRoute: WelcomeRoute,
  WishlistRoute: WishlistRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  CancelIdRoute: CancelIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  TripsIdRoute: TripsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
